version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - run: echo "build project"
      - run: npm install
      - run: npm build

workflows: 
    test_build:
      jobs:
        - test
        - build:
            requires:
              - test