apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-01-18T20:58:31Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: maxvmicro
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-01-18T20:58:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-18T20:58:31Z"
  name: maxvmicro-service
  namespace: default
  resourceVersion: "3008218"
  uid: 04c79233-f4b6-47e0-8185-42754a176675
spec:
  clusterIP: 10.16.14.189
  clusterIPs:
  - 10.16.14.189
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-to-80-tcp
    nodePort: 30142
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 8080-to-8080-tcp
    nodePort: 31061
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: maxvmicro
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
